const players2020 = [
    {
      "Name": "David Pastrnak",
      "Team": "BOS",
      "Position": "F",
      "Rk": 1,
      "Status": "Le Fevre",
      "FPts": 386.2,
      "FP/G": 5.52,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Leon Draisaitl",
      "Team": "EDM",
      "Position": "F",
      "Rk": 2,
      "Status": "Snyder",
      "FPts": 385.2,
      "FP/G": 5.43,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "John Carlson",
      "Team": "WSH",
      "Position": "D",
      "Rk": 3,
      "Status": "Le Fevre",
      "FPts": 357.4,
      "FP/G": 5.18,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Nathan MacKinnon",
      "Team": "COL",
      "Position": "F",
      "Rk": 4,
      "Status": "KV",
      "FPts": 348.8,
      "FP/G": 5.06,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Connor McDavid",
      "Team": "EDM",
      "Position": "F",
      "Rk": 5,
      "Status": "Leis",
      "FPts": 344.8,
      "FP/G": 5.39,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Auston Matthews",
      "Team": "TOR",
      "Position": "F",
      "Rk": 6,
      "Status": "Buckley",
      "FPts": 338.8,
      "FP/G": 4.84,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Roman Josi",
      "Team": "NSH",
      "Position": "D",
      "Rk": 7,
      "Status": "Scheuermann",
      "FPts": 333,
      "FP/G": 4.83,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Connor Hellebuyck",
      "Team": "WPG",
      "Position": "G",
      "Rk": 8,
      "Status": "Scheuermann",
      "FPts": 328.2,
      "FP/G": 5.66,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Alex Ovechkin",
      "Team": "WSH",
      "Position": "F",
      "Rk": 9,
      "Status": "Snyder",
      "FPts": 326.6,
      "FP/G": 4.8,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mika Zibanejad",
      "Team": "NYR",
      "Position": "F",
      "Rk": 10,
      "Status": "Scheuermann",
      "FPts": 324.2,
      "FP/G": 5.69,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Artemi Panarin",
      "Team": "NYR",
      "Position": "F",
      "Rk": 11,
      "Status": "Leis",
      "FPts": 318.2,
      "FP/G": 4.61,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Andrei Vasilevskiy",
      "Team": "TB",
      "Position": "G",
      "Rk": 12,
      "Status": "Larsen",
      "FPts": 317.5,
      "FP/G": 6.11,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jack Eichel",
      "Team": "BUF",
      "Position": "F",
      "Rk": 13,
      "Status": "Scheuermann",
      "FPts": 314.2,
      "FP/G": 4.62,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brad Marchand",
      "Team": "BOS",
      "Position": "F",
      "Rk": 14,
      "Status": "Erlandson",
      "FPts": 309.6,
      "FP/G": 4.42,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Nikita Kucherov",
      "Team": "TB",
      "Position": "F",
      "Rk": 15,
      "Status": "Le Fevre",
      "FPts": 302.2,
      "FP/G": 4.44,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Patrick Kane",
      "Team": "CHI",
      "Position": "F",
      "Rk": 16,
      "Status": "Mann",
      "FPts": 300,
      "FP/G": 4.29,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Max Pacioretty",
      "Team": "VGK",
      "Position": "F",
      "Rk": 17,
      "Status": "Buckley",
      "FPts": 290,
      "FP/G": 4.08,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Alex Pietrangelo",
      "Team": "STL",
      "Position": "D",
      "Rk": 18,
      "Status": "Mann",
      "FPts": 284.8,
      "FP/G": 4.07,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Victor Hedman",
      "Team": "TB",
      "Position": "D",
      "Rk": 19,
      "Status": "KV",
      "FPts": 283.2,
      "FP/G": 4.29,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "J.T. Miller",
      "Team": "VAN",
      "Position": "F",
      "Rk": 20,
      "Status": "Larsen",
      "FPts": 283,
      "FP/G": 4.1,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Kyle Connor",
      "Team": "WPG",
      "Position": "F",
      "Rk": 21,
      "Status": 'Sunny',
      "FPts": 283,
      "FP/G": 3.99,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Sebastian Aho",
      "Team": "CAR",
      "Position": "F",
      "Rk": 22,
      "Status": "Larsen",
      "FPts": 277.2,
      "FP/G": 4.08,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mark Scheifele",
      "Team": "WPG",
      "Position": "F",
      "Rk": 23,
      "Status": "Mann",
      "FPts": 270.8,
      "FP/G": 3.81,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jonathan Huberdeau",
      "Team": "FLA",
      "Position": "F",
      "Rk": 24,
      "Status": "Mann",
      "FPts": 266,
      "FP/G": 3.86,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tuukka Rask",
      "Team": "BOS",
      "Position": "G",
      "Rk": 25,
      "Status": "Le Fevre",
      "FPts": 261.3,
      "FP/G": 6.37,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brent Burns",
      "Team": "SJ",
      "Position": "D",
      "Rk": 26,
      "Status": "Erlandson",
      "FPts": 261,
      "FP/G": 3.73,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Blake Wheeler",
      "Team": "WPG",
      "Position": "F",
      "Rk": 27,
      "Status": "Larsen",
      "FPts": 261,
      "FP/G": 3.68,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Neal Pionk",
      "Team": "WPG",
      "Position": "D",
      "Rk": 28,
      "Status": "Le Fevre",
      "FPts": 260.6,
      "FP/G": 3.67,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jordan Binnington",
      "Team": "STL",
      "Position": "G",
      "Rk": 29,
      "Status": "Leis",
      "FPts": 259,
      "FP/G": 5.18,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Steven Stamkos",
      "Team": "TB",
      "Position": "F",
      "Rk": 30,
      "Status": "Buckley",
      "FPts": 259,
      "FP/G": 4.54,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Evgeni Malkin",
      "Team": "PIT",
      "Position": "F",
      "Rk": 31,
      "Status": "Mann",
      "FPts": 259,
      "FP/G": 4.71,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Elias Pettersson",
      "Team": "VAN",
      "Position": "F",
      "Rk": 32,
      "Status": "Leis",
      "FPts": 258,
      "FP/G": 3.79,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Carey Price",
      "Team": "MON",
      "Position": "G",
      "Rk": 33,
      "Status": 'Sunny',
      "FPts": 258,
      "FP/G": 4.45,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tony DeAngelo",
      "Team": "NYR",
      "Position": "D",
      "Rk": 34,
      "Status": "Scheuermann",
      "FPts": 256,
      "FP/G": 3.76,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Patrik Laine",
      "Team": "WPG",
      "Position": "F",
      "Rk": 35,
      "Status": "Leis",
      "FPts": 255.2,
      "FP/G": 3.75,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Frederik Andersen",
      "Team": "TOR",
      "Position": "G",
      "Rk": 36,
      "Status": 'Sunny',
      "FPts": 254.9,
      "FP/G": 4.9,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Patrice Bergeron",
      "Team": "BOS",
      "Position": "F",
      "Rk": 37,
      "Status": "Mann",
      "FPts": 251.8,
      "FP/G": 4.13,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brady Tkachuk",
      "Team": "OTT",
      "Position": "F",
      "Rk": 38,
      "Status": "Scheuermann",
      "FPts": 249.8,
      "FP/G": 3.52,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Kris Letang",
      "Team": "PIT",
      "Position": "D",
      "Rk": 39,
      "Status": "KV",
      "FPts": 249.2,
      "FP/G": 4.09,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Andrei Svechnikov",
      "Team": "CAR",
      "Position": "F",
      "Rk": 40,
      "Status": "Mann",
      "FPts": 248.4,
      "FP/G": 3.65,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "David Perron",
      "Team": "STL",
      "Position": "F",
      "Rk": 41,
      "Status": "Le Fevre",
      "FPts": 247.6,
      "FP/G": 3.49,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Shea Theodore",
      "Team": "VGK",
      "Position": "D",
      "Rk": 42,
      "Status": "Buckley",
      "FPts": 246.6,
      "FP/G": 3.47,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Matthew Tkachuk",
      "Team": "CGY",
      "Position": "F",
      "Rk": 43,
      "Status": "Scheuermann",
      "FPts": 241.8,
      "FP/G": 3.5,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mark Stone",
      "Team": "VGK",
      "Position": "F",
      "Rk": 44,
      "Status": "Erlandson",
      "FPts": 241.2,
      "FP/G": 3.71,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jeff Petry",
      "Team": "MON",
      "Position": "D",
      "Rk": 45,
      "Status": "Erlandson",
      "FPts": 240.6,
      "FP/G": 3.39,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Evander Kane",
      "Team": "SJ",
      "Position": "F",
      "Rk": 46,
      "Status": "KV",
      "FPts": 239.8,
      "FP/G": 3.75,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Anze Kopitar",
      "Team": "LA",
      "Position": "F",
      "Rk": 47,
      "Status": "Buckley",
      "FPts": 239.4,
      "FP/G": 3.42,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Elias Lindholm",
      "Team": "CGY",
      "Position": "F",
      "Rk": 48,
      "Status": "Le Fevre",
      "FPts": 237.2,
      "FP/G": 3.39,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Torey Krug",
      "Team": "BOS",
      "Position": "D",
      "Rk": 49,
      "Status": "Scheuermann",
      "FPts": 236.6,
      "FP/G": 3.88,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tom Wilson",
      "Team": "WSH",
      "Position": "F",
      "Rk": 50,
      "Status": "Snyder",
      "FPts": 236,
      "FP/G": 3.47,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ryan Nugent-Hopkins",
      "Team": "EDM",
      "Position": "F",
      "Rk": 51,
      "Status": "Larsen",
      "FPts": 234.8,
      "FP/G": 3.61,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Shea Weber",
      "Team": "MON",
      "Position": "D",
      "Rk": 52,
      "Status": "Buckley",
      "FPts": 234.4,
      "FP/G": 3.61,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mike Hoffman",
      "Team": "FLA",
      "Position": "F",
      "Rk": 53,
      "Status": "Le Fevre",
      "FPts": 234.2,
      "FP/G": 3.39,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Bryan Rust",
      "Team": "PIT",
      "Position": "F",
      "Rk": 54,
      "Status": "Erlandson",
      "FPts": 234.2,
      "FP/G": 4.26,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ryan Pulock",
      "Team": "NYI",
      "Position": "D",
      "Rk": 55,
      "Status": "Le Fevre",
      "FPts": 233.8,
      "FP/G": 3.44,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Cale Makar",
      "Team": "COL",
      "Position": "D",
      "Rk": 56,
      "Status": "Leis",
      "FPts": 233.4,
      "FP/G": 4.09,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mitchell Marner",
      "Team": "TOR",
      "Position": "F",
      "Rk": 57,
      "Status": "Snyder",
      "FPts": 232.6,
      "FP/G": 3.94,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jacob Markstrom",
      "Team": "VAN",
      "Position": "G",
      "Rk": 58,
      "Status": "Erlandson",
      "FPts": 232.5,
      "FP/G": 5.41,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ivan Provorov",
      "Team": "PHI",
      "Position": "D",
      "Rk": 59,
      "Status": "Erlandson",
      "FPts": 232.2,
      "FP/G": 3.37,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ryan Suter",
      "Team": "MIN",
      "Position": "D",
      "Rk": 60,
      "Status": "Erlandson",
      "FPts": 232.2,
      "FP/G": 3.37,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Teuvo Teravainen",
      "Team": "CAR",
      "Position": "F",
      "Rk": 61,
      "Status": "Leis",
      "FPts": 232,
      "FP/G": 3.41,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "John Tavares",
      "Team": "TOR",
      "Position": "F",
      "Rk": 62,
      "Status": "KV",
      "FPts": 231.8,
      "FP/G": 3.68,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Zach Werenski",
      "Team": "CBJ",
      "Position": "D",
      "Rk": 63,
      "Status": "KV",
      "FPts": 231.4,
      "FP/G": 3.67,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brayden Schenn",
      "Team": "STL",
      "Position": "F",
      "Rk": 64,
      "Status": "Leis",
      "FPts": 230.4,
      "FP/G": 3.25,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Marc-Andre Fleury",
      "Team": "VGK",
      "Position": "G",
      "Rk": 65,
      "Status": "Leis",
      "FPts": 230.3,
      "FP/G": 4.7,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Darnell Nurse",
      "Team": "EDM",
      "Position": "D",
      "Rk": 66,
      "Status": "Leis",
      "FPts": 228.8,
      "FP/G": 3.22,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jean-Gabriel Pageau",
      "Team": "NYI",
      "Position": "F",
      "Rk": 67,
      "Status": "Snyder",
      "FPts": 228.8,
      "FP/G": 3.41,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Quinn Hughes",
      "Team": "VAN",
      "Position": "D",
      "Rk": 68,
      "Status": 'Sunny',
      "FPts": 228.4,
      "FP/G": 3.36,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Travis Konecny",
      "Team": "PHI",
      "Position": "F",
      "Rk": 69,
      "Status": "Larsen",
      "FPts": 227.6,
      "FP/G": 3.45,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Oscar Klefbom",
      "Team": "EDM",
      "Position": "D",
      "Rk": 70,
      "Status": 'Sunny',
      "FPts": 227.6,
      "FP/G": 3.67,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "William Nylander",
      "Team": "TOR",
      "Position": "F",
      "Rk": 71,
      "Status": "KV",
      "FPts": 226.4,
      "FP/G": 3.33,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Sean Couturier",
      "Team": "PHI",
      "Position": "F",
      "Rk": 72,
      "Status": "Larsen",
      "FPts": 224.6,
      "FP/G": 3.26,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brayden Point",
      "Team": "TB",
      "Position": "F",
      "Rk": 73,
      "Status": "Snyder",
      "FPts": 224.6,
      "FP/G": 3.4,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Reilly Smith",
      "Team": "VGK",
      "Position": "F",
      "Rk": 74,
      "Status": "Buckley",
      "FPts": 224.2,
      "FP/G": 3.16,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Aleksander Barkov",
      "Team": "FLA",
      "Position": "F",
      "Rk": 75,
      "Status": "Scheuermann",
      "FPts": 224,
      "FP/G": 3.39,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tyler Seguin",
      "Team": "DAL",
      "Position": "F",
      "Rk": 76,
      "Status": "KV",
      "FPts": 223,
      "FP/G": 3.23,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Dougie Hamilton",
      "Team": "CAR",
      "Position": "D",
      "Rk": 77,
      "Status": "Larsen",
      "FPts": 222.6,
      "FP/G": 4.74,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Claude Giroux",
      "Team": "PHI",
      "Position": "F",
      "Rk": 78,
      "Status": "Buckley",
      "FPts": 221.2,
      "FP/G": 3.21,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Bo Horvat",
      "Team": "VAN",
      "Position": "F",
      "Rk": 79,
      "Status": "Snyder",
      "FPts": 221,
      "FP/G": 3.2,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Nikolaj Ehlers",
      "Team": "WPG",
      "Position": "F",
      "Rk": 80,
      "Status": "Erlandson",
      "FPts": 220.8,
      "FP/G": 3.11,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jaden Schwartz",
      "Team": "STL",
      "Position": "F",
      "Rk": 81,
      "Status": 'Sunny',
      "FPts": 220.2,
      "FP/G": 3.1,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Adam Fox",
      "Team": "NYR",
      "Position": "D",
      "Rk": 82,
      "Status": "Le Fevre",
      "FPts": 219.8,
      "FP/G": 3.14,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ben Bishop",
      "Team": "DAL",
      "Position": "G",
      "Rk": 83,
      "Status": "Buckley",
      "FPts": 219.7,
      "FP/G": 4.99,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Alexander Edler",
      "Team": "VAN",
      "Position": "D",
      "Rk": 84,
      "Status": "Le Fevre",
      "FPts": 219,
      "FP/G": 3.71,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tomas Tatar",
      "Team": "MON",
      "Position": "F",
      "Rk": 85,
      "Status": 'Sunny',
      "FPts": 218.8,
      "FP/G": 3.22,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ryan Strome",
      "Team": "NYR",
      "Position": "F",
      "Rk": 86,
      "Status": "KV",
      "FPts": 218.8,
      "FP/G": 3.13,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "David Rittich",
      "Team": "CGY",
      "Position": "G",
      "Rk": 87,
      "Status": "Leis",
      "FPts": 217.6,
      "FP/G": 4.53,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Timo Meier",
      "Team": "SJ",
      "Position": "F",
      "Rk": 88,
      "Status": "Le Fevre",
      "FPts": 217.6,
      "FP/G": 3.11,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jacob Trouba",
      "Team": "NYR",
      "Position": "D",
      "Rk": 89,
      "Status": "Erlandson",
      "FPts": 215.6,
      "FP/G": 3.08,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brock Nelson",
      "Team": "NYI",
      "Position": "F",
      "Rk": 90,
      "Status": "Scheuermann",
      "FPts": 214.6,
      "FP/G": 3.16,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "T.J. Oshie",
      "Team": "WSH",
      "Position": "F",
      "Rk": 91,
      "Status": "Buckley",
      "FPts": 212.6,
      "FP/G": 3.08,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mathew Barzal",
      "Team": "NYI",
      "Position": "F",
      "Rk": 92,
      "Status": 'Sunny',
      "FPts": 211.8,
      "FP/G": 3.11,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jamie Benn",
      "Team": "DAL",
      "Position": "F",
      "Rk": 93,
      "Status": "Erlandson",
      "FPts": 210,
      "FP/G": 3.04,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jonathan Marchessault",
      "Team": "VGK",
      "Position": "F",
      "Rk": 94,
      "Status": "Le Fevre",
      "FPts": 209.8,
      "FP/G": 3.18,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Thomas Chabot",
      "Team": "OTT",
      "Position": "D",
      "Rk": 95,
      "Status": 'Sunny',
      "FPts": 209.6,
      "FP/G": 2.95,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Rasmus Ristolainen",
      "Team": "BUF",
      "Position": "D",
      "Rk": 96,
      "Status": "Larsen",
      "FPts": 209,
      "FP/G": 3.03,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mikhail Sergachev",
      "Team": "TB",
      "Position": "D",
      "Rk": 97,
      "Status": "Buckley",
      "FPts": 208.6,
      "FP/G": 2.98,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mark Giordano",
      "Team": "CGY",
      "Position": "D",
      "Rk": 98,
      "Status": 'Sunny',
      "FPts": 208.2,
      "FP/G": 3.47,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Dylan Larkin",
      "Team": "DET",
      "Position": "F",
      "Rk": 99,
      "Status": "Scheuermann",
      "FPts": 207.8,
      "FP/G": 2.93,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Drew Doughty",
      "Team": "LA",
      "Position": "D",
      "Rk": 100,
      "Status": "KV",
      "FPts": 207,
      "FP/G": 3.09,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ryan O'Reilly",
      "Team": "STL",
      "Position": "F",
      "Rk": 101,
      "Status": "Larsen",
      "FPts": 206.8,
      "FP/G": 2.91,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jakub Vrana",
      "Team": "WSH",
      "Position": "F",
      "Rk": 102,
      "Status": 'Sunny',
      "FPts": 206.2,
      "FP/G": 2.99,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Anders Lee",
      "Team": "NYI",
      "Position": "F",
      "Rk": 103,
      "Status": "Mann",
      "FPts": 206,
      "FP/G": 3.03,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jaccob Slavin",
      "Team": "CAR",
      "Position": "D",
      "Rk": 104,
      "Status": "Scheuermann",
      "FPts": 205.2,
      "FP/G": 3.02,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ryan Graves",
      "Team": "COL",
      "Position": "D",
      "Rk": 105,
      "Status": "Snyder",
      "FPts": 205,
      "FP/G": 2.97,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Taylor Hall",
      "Team": "ARI",
      "Position": "F",
      "Rk": 106,
      "Status": "Erlandson",
      "FPts": 204.6,
      "FP/G": 3.15,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Kevin Fiala",
      "Team": "MIN",
      "Position": "F",
      "Rk": 107,
      "Status": "Mann",
      "FPts": 204,
      "FP/G": 3.19,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Blake Coleman",
      "Team": "TB",
      "Position": "F",
      "Rk": 108,
      "Status": 'Sunny',
      "FPts": 203.6,
      "FP/G": 3.08,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ryan Ellis",
      "Team": "NSH",
      "Position": "D",
      "Rk": 109,
      "Status": "Leis",
      "FPts": 203.4,
      "FP/G": 4.15,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tanner Pearson",
      "Team": "VAN",
      "Position": "F",
      "Rk": 110,
      "Status": "Buckley",
      "FPts": 203.2,
      "FP/G": 2.94,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Matt Niskanen",
      "Team": "PHI",
      "Position": "D",
      "Rk": 111,
      "Status": "Buckley",
      "FPts": 203,
      "FP/G": 2.99,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Aaron Ekblad",
      "Team": "FLA",
      "Position": "D",
      "Rk": 112,
      "Status": "Scheuermann",
      "FPts": 203,
      "FP/G": 3.03,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Pierre-Luc Dubois",
      "Team": "CBJ",
      "Position": "F",
      "Rk": 113,
      "Status": "Snyder",
      "FPts": 202.2,
      "FP/G": 2.89,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Keith Yandle",
      "Team": "FLA",
      "Position": "D",
      "Rk": 114,
      "Status": "Larsen",
      "FPts": 201.8,
      "FP/G": 2.92,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Kyle Palmieri",
      "Team": "NJ",
      "Position": "F",
      "Rk": 115,
      "Status": "Larsen",
      "FPts": 201.4,
      "FP/G": 3.1,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Carter Hart",
      "Team": "PHI",
      "Position": "G",
      "Rk": 116,
      "Status": "Mann",
      "FPts": 200.5,
      "FP/G": 4.66,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Filip Forsberg",
      "Team": "NSH",
      "Position": "F",
      "Rk": 117,
      "Status": "KV",
      "FPts": 200.4,
      "FP/G": 3.18,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Johnny Gaudreau",
      "Team": "CGY",
      "Position": "F",
      "Rk": 118,
      "Status": "Erlandson",
      "FPts": 200.4,
      "FP/G": 2.86,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Alex Killorn",
      "Team": "TB",
      "Position": "F",
      "Rk": 119,
      "Status": 'Sunny',
      "FPts": 198.6,
      "FP/G": 2.92,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tyson Barrie",
      "Team": "TOR",
      "Position": "D",
      "Rk": 120,
      "Status": "Buckley",
      "FPts": 198.4,
      "FP/G": 2.83,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Ondrej Palat",
      "Team": "TB",
      "Position": "F",
      "Rk": 121,
      "Status": "Le Fevre",
      "FPts": 198,
      "FP/G": 2.87,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jared Spurgeon",
      "Team": "MIN",
      "Position": "D",
      "Rk": 122,
      "Status": "KV",
      "FPts": 196.8,
      "FP/G": 3.17,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Robin Lehner",
      "Team": "VGK",
      "Position": "G",
      "Rk": 123,
      "Status": "Le Fevre",
      "FPts": 196.5,
      "FP/G": 5.46,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Sean Monahan",
      "Team": "CGY",
      "Position": "F",
      "Rk": 124,
      "Status": 'Sunny',
      "FPts": 195.8,
      "FP/G": 2.8,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mattias Ekholm",
      "Team": "NSH",
      "Position": "D",
      "Rk": 125,
      "Status": "Leis",
      "FPts": 195.8,
      "FP/G": 2.88,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Zach Parise",
      "Team": "MIN",
      "Position": "F",
      "Rk": 126,
      "Status": "Buckley",
      "FPts": 195.4,
      "FP/G": 2.83,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Sergei Bobrovsky",
      "Team": "FLA",
      "Position": "G",
      "Rk": 127,
      "Status": "Larsen",
      "FPts": 192.5,
      "FP/G": 3.85,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Braden Holtby",
      "Team": "WSH",
      "Position": "G",
      "Rk": 128,
      "Status": "KV",
      "FPts": 192,
      "FP/G": 4,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Gabriel Landeskog",
      "Team": "COL",
      "Position": "F",
      "Rk": 129,
      "Status": "Erlandson",
      "FPts": 191.8,
      "FP/G": 3.55,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Pavel Francouz",
      "Team": "COL",
      "Position": "G",
      "Rk": 130,
      "Status": "Erlandson",
      "FPts": 191.7,
      "FP/G": 5.64,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Semyon Varlamov",
      "Team": "NYI",
      "Position": "G",
      "Rk": 131,
      "Status": "Le Fevre",
      "FPts": 191.6,
      "FP/G": 4.26,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Alex DeBrincat",
      "Team": "CHI",
      "Position": "F",
      "Rk": 132,
      "Status": "Leis",
      "FPts": 190.6,
      "FP/G": 2.72,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Miro Heiskanen",
      "Team": "DAL",
      "Position": "D",
      "Rk": 133,
      "Status": "Snyder",
      "FPts": 190,
      "FP/G": 2.79,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "John Gibson",
      "Team": "ANA",
      "Position": "G",
      "Rk": 134,
      "Status": "Larsen",
      "FPts": 189.9,
      "FP/G": 3.72,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Tyler Toffoli",
      "Team": "VAN",
      "Position": "F",
      "Rk": 135,
      "Status": "Larsen",
      "FPts": 189.4,
      "FP/G": 2.79,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Anthony Cirelli",
      "Team": "TB",
      "Position": "F",
      "Rk": 136,
      "Status": 'Sunny',
      "FPts": 188.8,
      "FP/G": 2.78,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Rasmus Dahlin",
      "Team": "BUF",
      "Position": "D",
      "Rk": 137,
      "Status": "Scheuermann",
      "FPts": 188.4,
      "FP/G": 3.19,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Nicklas Backstrom",
      "Team": "WSH",
      "Position": "F",
      "Rk": 138,
      "Status": "Buckley",
      "FPts": 188.2,
      "FP/G": 3.09,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jakub Voracek",
      "Team": "PHI",
      "Position": "F",
      "Rk": 139,
      "Status": "KV",
      "FPts": 188,
      "FP/G": 2.72,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "William Karlsson",
      "Team": "VGK",
      "Position": "F",
      "Rk": 140,
      "Status": "Scheuermann",
      "FPts": 188,
      "FP/G": 2.98,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Evgenii Dadonov",
      "Team": "FLA",
      "Position": "F",
      "Rk": 141,
      "Status": "Leis",
      "FPts": 187.4,
      "FP/G": 2.72,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Rickard Rakell",
      "Team": "ANA",
      "Position": "F",
      "Rk": 142,
      "Status": "Larsen",
      "FPts": 185,
      "FP/G": 2.85,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brendan Gallagher",
      "Team": "MON",
      "Position": "F",
      "Rk": 143,
      "Status": "Larsen",
      "FPts": 184.2,
      "FP/G": 3.12,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Oliver Ekman-Larsson",
      "Team": "ARI",
      "Position": "D",
      "Rk": 144,
      "Status": "Snyder",
      "FPts": 183.2,
      "FP/G": 2.78,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Damon Severson",
      "Team": "NJ",
      "Position": "D",
      "Rk": 145,
      "Status": "Mann",
      "FPts": 182.6,
      "FP/G": 2.65,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Sam Reinhart",
      "Team": "BUF",
      "Position": "F",
      "Rk": 146,
      "Status": "Le Fevre",
      "FPts": 181.8,
      "FP/G": 2.63,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jakob Chychrun",
      "Team": "ARI",
      "Position": "D",
      "Rk": 147,
      "Status": "Le Fevre",
      "FPts": 180.4,
      "FP/G": 2.86,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Corey Crawford",
      "Team": "CHI",
      "Position": "G",
      "Rk": 148,
      "Status": "Mann",
      "FPts": 179.8,
      "FP/G": 4.5,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Kevin Shattenkirk",
      "Team": "TB",
      "Position": "D",
      "Rk": 149,
      "Status": "Leis",
      "FPts": 179.6,
      "FP/G": 2.57,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Juuse Saros",
      "Team": "NSH",
      "Position": "G",
      "Rk": 150,
      "Status": "Erlandson",
      "FPts": 178.4,
      "FP/G": 4.46,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Petr Mrazek",
      "Team": "CAR",
      "Position": "G",
      "Rk": 151,
      "Status": 'Sunny',
      "FPts": 176.2,
      "FP/G": 4.4,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Brock Boeser",
      "Team": "VAN",
      "Position": "F",
      "Rk": 152,
      "Status": "Leis",
      "FPts": 174.8,
      "FP/G": 3.07,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Andre Burakovsky",
      "Team": "COL",
      "Position": "F",
      "Rk": 153,
      "Status": 'Sunny',
      "FPts": 174.6,
      "FP/G": 3.01,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Philipp Grubauer",
      "Team": "COL",
      "Position": "G",
      "Rk": 154,
      "Status": "KV",
      "FPts": 174.4,
      "FP/G": 4.84,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Evgeny Kuznetsov",
      "Team": "WSH",
      "Position": "F",
      "Rk": 155,
      "Status": "Snyder",
      "FPts": 173.8,
      "FP/G": 2.76,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Matt Dumba",
      "Team": "MIN",
      "Position": "D",
      "Rk": 156,
      "Status": "Mann",
      "FPts": 173,
      "FP/G": 2.51,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Joonas Korpisalo",
      "Team": "CBJ",
      "Position": "G",
      "Rk": 157,
      "Status": "Snyder",
      "FPts": 172,
      "FP/G": 4.65,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "John Klingberg",
      "Team": "DAL",
      "Position": "D",
      "Rk": 158,
      "Status": "Larsen",
      "FPts": 169.2,
      "FP/G": 2.92,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Darcy Kuemper",
      "Team": "ARI",
      "Position": "G",
      "Rk": 159,
      "Status": "Scheuermann",
      "FPts": 169.1,
      "FP/G": 5.83,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Clayton Keller",
      "Team": "ARI",
      "Position": "F",
      "Rk": 160,
      "Status": "Leis",
      "FPts": 168.8,
      "FP/G": 2.41,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Anthony Beauvillier",
      "Team": "NYI",
      "Position": "F",
      "Rk": 161,
      "Status": "KV",
      "FPts": 167.8,
      "FP/G": 2.47,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Sidney Crosby",
      "Team": "PIT",
      "Position": "F",
      "Rk": 162,
      "Status": "Scheuermann",
      "FPts": 167.6,
      "FP/G": 4.09,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Joel Armia",
      "Team": "MON",
      "Position": "F",
      "Rk": 163,
      "Status": "Le Fevre",
      "FPts": 166.6,
      "FP/G": 2.87,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Patric Hornqvist",
      "Team": "PIT",
      "Position": "F",
      "Rk": 164,
      "Status": "KV",
      "FPts": 165.2,
      "FP/G": 3.18,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Duncan Keith",
      "Team": "CHI",
      "Position": "D",
      "Rk": 165,
      "Status": "Mann",
      "FPts": 164,
      "FP/G": 2.69,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mikko Rantanen",
      "Team": "COL",
      "Position": "F",
      "Rk": 166,
      "Status": "Larsen",
      "FPts": 163.8,
      "FP/G": 3.9,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jason Zucker",
      "Team": "PIT",
      "Position": "F",
      "Rk": 167,
      "Status": "Scheuermann",
      "FPts": 163.2,
      "FP/G": 2.72,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Vincent Trocheck",
      "Team": "CAR",
      "Position": "F",
      "Rk": 168,
      "Status": "Scheuermann",
      "FPts": 162.6,
      "FP/G": 2.62,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Victor Olofsson",
      "Team": "BUF",
      "Position": "F",
      "Rk": 169,
      "Status": "Mann",
      "FPts": 162.6,
      "FP/G": 3.01,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Mike Smith",
      "Team": "EDM",
      "Position": "G",
      "Rk": 170,
      "Status": "Snyder",
      "FPts": 162.4,
      "FP/G": 4.16,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jordan Eberle",
      "Team": "NYI",
      "Position": "F",
      "Rk": 171,
      "Status": "KV",
      "FPts": 162.4,
      "FP/G": 2.8,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "David Krejci",
      "Team": "BOS",
      "Position": "F",
      "Rk": 172,
      "Status": "Snyder",
      "FPts": 158.6,
      "FP/G": 2.6,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Matt Murray",
      "Team": "PIT",
      "Position": "G",
      "Rk": 173,
      "Status": "Buckley",
      "FPts": 156.5,
      "FP/G": 4.12,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Anthony Mantha",
      "Team": "DET",
      "Position": "F",
      "Rk": 174,
      "Status": "Erlandson",
      "FPts": 155.8,
      "FP/G": 3.62,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Jonathan Quick",
      "Team": "LA",
      "Position": "G",
      "Rk": 175,
      "Status": "Buckley",
      "FPts": 155.3,
      "FP/G": 3.7,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Matt Duchene",
      "Team": "NSH",
      "Position": "F",
      "Rk": 176,
      "Status": "Snyder",
      "FPts": 153.2,
      "FP/G": 2.32,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Morgan Rielly",
      "Team": "TOR",
      "Position": "D",
      "Rk": 177,
      "Status": 'Sunny',
      "FPts": 149.8,
      "FP/G": 3.19,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Zach Hyman",
      "Team": "TOR",
      "Position": "F",
      "Rk": 178,
      "Status": "Erlandson",
      "FPts": 149.4,
      "FP/G": 2.93,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "P.K. Subban",
      "Team": "NJ",
      "Position": "D",
      "Rk": 179,
      "Status": "Snyder",
      "FPts": 149,
      "FP/G": 2.19,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Sami Vatanen",
      "Team": "CAR",
      "Position": "D",
      "Rk": 180,
      "Status": "Mann",
      "FPts": 141,
      "FP/G": 3,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Thomas Greiss",
      "Team": "NYI",
      "Position": "G",
      "Rk": 181,
      "Status": "Snyder",
      "FPts": 138.1,
      "FP/G": 4.45,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Alec Martinez",
      "Team": "VGK",
      "Position": "D",
      "Rk": 182,
      "Status": 'Sunny',
      "FPts": 121.4,
      "FP/G": 2.38,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Cam Atkinson",
      "Team": "CBJ",
      "Position": "F",
      "Rk": 183,
      "Status": "Buckley",
      "FPts": 118,
      "FP/G": 2.68,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Thatcher Demko",
      "Team": "VAN",
      "Position": "G",
      "Rk": 184,
      "Status": "KV",
      "FPts": 112.4,
      "FP/G": 4.16,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Andreas Athanasiou",
      "Team": "EDM",
      "Position": "F",
      "Rk": 185,
      "Status": "Mann",
      "FPts": 107.4,
      "FP/G": 1.95,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Kailer Yamamoto",
      "Team": "EDM",
      "Position": "F",
      "Rk": 186,
      "Status": "Erlandson",
      "FPts": 91.4,
      "FP/G": 3.39,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Igor Shesterkin",
      "Team": "NYR",
      "Position": "G",
      "Rk": 187,
      "Status": "Mann",
      "FPts": 91.3,
      "FP/G": 7.61,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Vladimir Tarasenko",
      "Team": "STL",
      "Position": "F",
      "Rk": 188,
      "Status": "Mann",
      "FPts": 37,
      "FP/G": 3.7,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    },
    {
      "Name": "Dustin Byfuglien",
      "Team": "WPG",
      "Position": "D",
      "Rk": 189,
      "Status": "Leis",
      "FPts": 0,
      "FP/G": 0,
      "": "",
      "__1": "",
      "__2": "",
      "__3": ""
    }
  ]

const GMs = {
    Buckley: {
        id: 'Buckley',
        s2020: {
            wins: 7,
            losses: 14,
            playoffFinish: 0,
            players: players2020.filter((el) => Status === 'Buckley')
        },
        championships:[],
        henicups:[2019]
        
    },
    Erlandson: {
        id: 'Erlandson',
        s2020: {
            wins:11,
            losses: 10,
            playoffFinish: 0
        },
        championships:[],
        henicups:[]
    },
    Larsen: {
        id: 'Larsen',
        s2020: {
            wins: 12,
            losses: 9,
            playoffFinish: 0
        },
        championships:[],
        henicups:[]
    },
    'Le Fevre': {
        id: 'Le Fevre',
        s2020: {
            wins: 10,
            losses: 11,
            playoffFinish: 0
        },
        championships:[],
        henicups:[2013,2014,2016]
    },
    Leis: {
        id: 'Leis',
        s2020: {
            wins: 7,
            losses: 14,
            playoffFinish: 0
        },
        championships:[],
        henicups:[2018]
    },
    Mann: {
        id: 'Mann',
        s2020: {
            wins: 15,
            losses: 6,
            playoffFinish: 0
        },
        championships:[2018,2019],
        henicups:[]
    },
    Scheuermann: {
        id: 'Scheuermann',
        s2020: {
            wins: 7,
            losses: 14,
            playoffFinish: 0
        },
        championships:[2017],
        henicups:[]
    },
    Snyder: {
        id: 'Snyder',
        s2020: {
            wins: 9,
            losses: 12,
            playoffFinish: 0
        },
        championships:[],
        henicups:[]
    },
    'Varley Jr.': {
        id: 'Sunny',
        s2020: {
            wins: 7,
            losses: 14,
            playoffFinish: 0
        },
        championships:[2014, 2015, 2016],
        henicups:[]
    },
    "Varley Sr.":  {
        id: 'KV',
        s2020: {
            wins: 7,
            losses: 14,
            playoffFinish: 0
        },
        championships:[],
        henicups:[],
        playoffFinish: 0
    }
}

console.log(GMs.Buckley)